pipeline:
  identifier: Build_chuckaude_test1_hello_java_1755793579203
  name: Build hello-java
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1755793504106
        repoName: chuckaude-test1/hello-java
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: Maven Build
                  spec:
                    connectorRef: account.harnessImage
                    image: maven:3-eclipse-temurin-21
                    shell: Sh
                    command: mvn -B -DskipTests package
                  timeout: ""
                  type: Run
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
