pipeline:
  identifier: Build_chuckaude_test1_hello_java_1755793579203
  name: Build hello-java
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1755793504106
        repoName: chuckaude-test1/hello-java
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: Maven Build
                  spec:
                    connectorRef: account.harnessImage
                    image: maven:3-eclipse-temurin-21
                    shell: Sh
                    command: mvn -B -DskipTests package
                  timeout: ""
                  type: Run
              - step:
                  type: Run
                  name: Polaris Scan
                  identifier: Polaris_Scan
                  spec:
                    connectorRef: account.harnessImage
                    image: maven:3-eclipse-temurin-21
                    shell: Sh
                    command: |-
                      env | sort
                      apt-get -q update && apt-get -q install -y curl file unzip
                      curl -fLsS -o bridge.zip $BRIDGECLI_LINUX64 && unzip -qo -d /tmp bridge.zip && rm -f bridge.zip
                      /tmp/bridge-cli-bundle-linux64/bridge-cli --verbose --stage polaris \
                          polaris.application.name=chuckaude-$DRONE_REPO_NAME \
                          polaris.project.name=$DRONE_REPO_NAME \
                          polaris.branch.name=$DRONE_REPO_BRANCH \
                          polaris.assessment.types=SAST,SCA
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
  variables:
    - name: BRIDGE_POLARIS_SERVERURL
      type: String
      description: ""
      required: false
      value: https://poc.polaris.blackduck.com
    - name: BRIDGE_POLARIS_ACCESSTOKEN
      type: Secret
      description: ""
      required: false
      value: polaris-poc-aude-setest
    - name: BRIDGECLI_LINUX64
      type: String
      description: ""
      required: false
      value: https://repo.blackduck.com/artifactory/bds-integrations-release/com/blackduck/integration/bridge/binaries/bridge-cli-bundle/latest/bridge-cli-bundle-linux64.zip
